### ISSUE TITLE
Question: Possible to find CNI Pod?

### ISSUE THREAD

**Issue by andrewrynhard** [containerd/go-cni#51]
I apologize in advance if this isn't the right place for this question. I'm trying to identify the pod responsible for providing the CNI to a node. I have a use case where I need to destroy all pods on a node, without using Kubernetes, and I need to destroy the CNI pod last. The reason I need to do this is because in the case of cilium, if I destroy the cilium pod first, I get the following error when attempting to destroy subsequent pods:

```
StopPodSandbox "c0e0d734fbf5d44c44cac7ca535475a0a747b55abee1782c842fc270b1a254e6" from runtime service failed: rpc error: code = Unknown desc = failed to destroy network for sandbox "c0e0d734fbf5d44c44cac7ca535475a0a747b55abee1782c842fc270b1a254e6": unable to connect to Cilium daemon: failed to create cilium agent client after 30.000000 seconds timeout: Get http:///var/run/cilium/cilium.sock/v1/config: dial unix /var/run/cilium/cilium.sock: connect: no such file or directory
```

I don't know if I will face something similar with other CNIs, and I'd like to discover the CNI pod dynamically so that I can destroy it last. So maybe I have 2 questions:

1. Is it possible to discover which pod is providing the CNI to a given node?
2. If so, can I use this package to do so?

I am posting these questions here since I am using containerd as the CRI, so I figured the maintainers of this package would know best. I appreciate any kind of help you guys can offer 🙂.

**Comment by fuweid** [comment]
@andrewrynhard I think the pod providing CNI service is using host-networking in most cases. If so, you can delete non-host-networking pods first and then delete host-networking pods. Hope it can help.
