### ISSUE TITLE
Support CNI CHECK Command

### ISSUE THREAD

**Issue by MikeZappa87** [containerd/go-cni#77]
I noticed that containerd does not implement the CNI CHECK command, it does implement ADD/DEL. Talking with @mikebrow on this one. It sounds like adding it here (go-cni) is a good first step. 

For your reading pleasure:
https://github.com/containernetworking/cni/blob/master/SPEC.md#check-check-containers-networking-is-as-expected

**Comment by fuweid** [comment]
closed by #80
